### ISSUE TITLE
Cookbook throws an error when we specify new agent pool

### ISSUE THREAD

**Issue by raghureddy45** [microsoft/azure-pipelines-agent-cookbook#38]
I was able to install an agent into an existing pool. However, When I specify a new agent pool to `vsts_pool` property it is throwing an error saying that pool doesn't exist.  it is supposed to creating the agent pool and then configure the agent into the pool right?

**Comment by raghureddy45** [comment]
any update on this?

**Comment by ehanlon** [comment]
The resource expects an existing pool on Azure DevOps.

If you're looking for an automated way to provision a pool, you might want to check out the new [Azure DevOps provider for Terraform](https://www.terraform.io/docs/providers/azuredevops/r/agent_pool.html).
